USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/meizu/mx4pro/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := exynos5
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a15
TARGET_SLSI_VARIANT := insignal
TARGET_SOC := exynos5430
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
USE_OPENGL_RENDERER := true
TARGET_USE_QCOM_BIONIC_OPTIMIZATION := true

BOARD_EGL_CFG := device/meizu/mx4pro/egl.cfg
BOARD_USES_ALSA_AUDIO := true

TARGET_BOOTLOADER_BOARD_NAME := m76
TARGET_BOARD_INFO_FILE := device/meizu/mx4pro/board-info.txt

TARGET_NO_RADIOIMAGE := true
TARGET_PREBUILT_KERNEL := device/meizu/mx4pro/kernel
BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x26000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x26000000 --tags_offset 0x00000100 --dt device/meizu/mx4pro/dt.img
KERNEL_EXFAT_MODULE_NAME := "exfat"
#KERNEL_NTFS_MODULE_NAME := "ntfs"

#Recovery
#TARGET_RECOVERY_FSTAB := device/meizu/mx4pro/recovery.fstab
#RECOVERY_FSTAB_VERSION := 2

TARGET_BOOTANIMATION_SIZE := 2560x1440
#TWRP
RECOVERY_SDCARD_ON_DATA := true
TW_NO_REBOOT_BOOTLOADER := true
DEVICE_RESOLUTION := 1080x1920
TW_MAX_BRIGHTNESS := 1680
PRODUCT_COPY_FILES += device/meizu/mx4pro/twrp.fstab:recovery/root/etc/twrp.fstab

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 8388608
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1610612736
BOARD_USERDATAIMAGE_PARTITION_SIZE := 28600958976
BOARD_FLASH_BLOCK_SIZE := 131072

# Assert
TARGET_OTA_ASSERT_DEVICE := mx4pro,m76

